module.exports = {
    ORDER_AWAITS_CONFIRMATION: 'ORDER_AWAITS_CONFIRMATION',
    PASSWORD_WAS_CHANGE: 'PASSWORD_WAS_CHANGE',
    USER_ACTIVATION: 'USER_ACTIVATION',
    USER_REGISTRATION: 'USER_REGISTRATION',
    USER_FORGOT_PASSWORD: 'USER_FORGOT_PASSWORD',
    USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD'
};
